### ISSUE TITLE
Navigation Sidebar is not stateful

### ISSUE THREAD

**Issue by myrrlyn** [steveklabnik/doxidize#94] opened 2018-04-04 02:39 UTC
When changing pages with the navigation sidebar, the new page load always results in the first section being expanded and all the others being collapsed. While browsing through sections other than the first, this is an inconvenience.

Should the sidebar maintain state across page loads, and always open to the most-recently-used section?

**Comment by mgattozzi** [comment] 2018-04-04 03:12
Related to https://github.com/steveklabnik/doxidize/issues/73. It should be stateful and only change content of the section displaying docs.

**Comment by rfdonnelly** [comment] 2018-04-09 15:29
Dupe of #40

**Closed** 2018-04-09 21:45 UTC
Labels: bug, question
