### ISSUE TITLE
Submenu should be visible after selection

### ISSUE THREAD

**Issue by droundy** [steveklabnik/doxidize#109] opened 2018-04-23 21:21 UTC
When interacting with the doxidize documentation, I noticed that if I clicked on a sub-menu (e.g. User's Guide/Workflow), the new page I'm brought to opens with "User's Guide" collapsed.  It would be better to leave that submenu visible, since I'm likely to want to navigate to nearby pages.

**Comment by rfdonnelly** [comment] 2018-04-23 22:27
Dupe of #40

**Closed** 2018-05-21 02:04 UTC
